# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "trackless_triggers"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Patterson", "Christian Eager", "Alexander Presber"]
  s.date = "2013-03-05"
  s.description = "Adds support for MySQL triggers in ActiveRecord"
  s.email = "apresber@jovoto.com"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "CHANGELOG",
    "MIT-LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/trackless_triggers.rb",
    "trackless_triggers.gemspec"
  ]
  s.homepage = "https://github.com/jovoto-team/trackless_triggers"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Adds support for MySQL triggers in ActiveRecord"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

